connect:
  facebook:
    key: "174349512614081"
    secret: "c81d7efe209761920c59f6258154014d"
    label: "Facebook"
  google:
    key: "internshipdatabase.org"
    secret: "TtTHtxlE0fFwNf4Vc56JpWFO"
    label: "Google"